CREATE TABLE IF NOT EXISTS player_fairs (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  save JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS fair_completions (
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  run_id UUID NOT NULL,
  game_id TEXT NOT NULL,
  stars INTEGER NOT NULL CHECK(stars BETWEEN 1 AND 3),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY(user_id,run_id)
);
