ALTER TABLE fair_completions ADD COLUMN IF NOT EXISTS course_id TEXT NOT NULL DEFAULT '';
ALTER TABLE fair_completions ADD COLUMN IF NOT EXISTS elapsed_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE fair_completions ADD COLUMN IF NOT EXISTS feathers INTEGER NOT NULL DEFAULT 0;
