import Link from "next/link";
import VillageWelcome from "@/components/VillageWelcome";
import SkillMap from "@/components/SkillMap";
import AdaptivePlan from "@/components/AdaptivePlan";
import LiveSnapshot from "@/components/LiveSnapshot";
import DailyQuestBoard from "@/components/DailyQuestBoard";
import CampaignSpotlight from "@/components/CampaignSpotlight";
import WorldSelect from "@/components/WorldSelect";
import { games } from "@/data/learning";

export default function Home(){return <div className="page-wrap"><header className="topbar"><div><span className="eyebrow">ENGLISH ADVENTURE</span><h1>Your next quest is ready.</h1><p>Every answer changes your build. Weak skills create recovery quests; your goal decides where today&apos;s run begins.</p></div><div className="top-actions"><span className="streak">🔥 keep the run alive</span><Link className="button ghost" href="/onboarding">Tune build</Link><Link className="button primary" href="/worlds">Open world map →</Link></div></header><VillageWelcome/><LiveSnapshot/><section className="hero-grid"><CampaignSpotlight/><DailyQuestBoard/></section><AdaptivePlan/><section className="panel"><div className="section-heading"><div><span className="eyebrow">WORLD SELECT</span><h2>Choose where to play next</h2></div><Link href="/worlds" className="text-link">Open full map →</Link></div><WorldSelect/></section><SkillMap/><section className="split-grid"><article className="panel"><div className="section-heading"><div><span className="eyebrow">ARCADE</span><h2>Quick XP runs</h2></div><Link href="/games" className="text-link">All games →</Link></div><div className="quick-games">{games.slice(0,4).map(game=><Link className="quick-game" href={game.href} key={game.slug}><span>{game.icon}</span><div><strong>{game.name}</strong><small>{game.skill} · {game.minutes} min</small></div><b>→</b></Link>)}</div></article><article className="panel"><div className="section-heading"><div><span className="eyebrow">HOW THE GAME LEARNS YOU</span><h2>Mistakes become content</h2></div></div><div className="quest-list"><div className="quest"><span className="check">①</span><span>Play any quest or mini-game</span><small>evidence</small></div><div className="quest"><span className="check">②</span><span>Weak concepts enter Recovery</span><small>SRS</small></div><div className="quest"><span className="check">③</span><span>Daily quests adapt automatically</span><small>rules</small></div><div className="quest"><span className="check">④</span><span>Worlds and bosses unlock from proof</span><small>mastery</small></div></div></article></section></div>}
