"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { BossState, completeBoss, getProgression, recordAttempt, sendConversation } from "@/lib/api";

type Message = { role: "agent" | "user"; content: string };

export default function AirportMission() {
  const [boss,setBoss]=useState<BossState|null>(null);
  const [messages,setMessages]=useState<Message[]>([{role:"agent",content:"Good afternoon. How can I help you with your flight today?"}]);
  const [objective,setObjective]=useState("Explain that you missed your flight and ask to be rebooked.");
  const [text,setText]=useState("");const [turns,setTurns]=useState(0);const [busy,setBusy]=useState(false);const [claiming,setClaiming]=useState(false);const [notice,setNotice]=useState("");
  useEffect(()=>{getProgression().then(s=>setBoss(s.bosses.find(b=>b.id==="airport-crisis")??null)).catch(()=>setNotice("Progression service is offline."))},[]);
  const checkpoints=boss?.checkpoints??[];const unlocked=!!boss?.unlocked;const won=!!boss?.cleared;const progress=useMemo(()=>{const ready=checkpoints.filter(c=>c.complete).length;return (ready+(won?1:0))/4*100},[checkpoints,won]);
  async function chat(e:FormEvent){e.preventDefault();if(!text.trim()||busy||!unlocked)return;const userText=text.trim();setText("");setBusy(true);const next=[...messages,{role:"user" as const,content:userText}];setMessages(next);try{const result=await sendConversation(userText,next.map(m=>({role:m.role==="agent"?"assistant":"user",content:m.content})));setMessages([...next,{role:"agent",content:result.reply}]);setObjective(result.objective);const nextTurn=turns+1;setTurns(nextTurn);await recordAttempt({skill:"Speaking",activity:"npc-conversation",itemKey:`airport-npc-${nextTurn}`,prompt:objective,answer:userText,accuracy:.9});if(nextTurn>=3){setClaiming(true);const state=await completeBoss("airport-crisis",92);setBoss(state.bosses.find(b=>b.id==="airport-crisis")??null);setNotice("Boss cleared. +150 XP and Airport Wings unlocked.")}}catch(e){setNotice(e instanceof Error?e.message:"Coach unavailable") }finally{setBusy(false);setClaiming(false)}}
  return <div className="mission-shell"><section className="mission-header"><div><span className="eyebrow light">TRAVEL BOSS · AIRPORT</span><h1>You missed your flight.</h1><p>Checkpoints are unlocked only by real learning evidence. No manual ready button.</p></div><div className="mission-progress"><strong>{Math.round(progress)}%</strong><small>mission</small></div></section>{notice&&<div className="feedback-banner">{notice}</div>}<div className="mission-stage-grid">{checkpoints.map((stage,i)=><article className={`mission-stage ${stage.complete?"complete":""}`} key={stage.id}><span>0{i+1}</span><div><small>{stage.skill}</small><strong>{stage.title}</strong></div><div className="mission-stage-actions"><Link href={stage.route}>{stage.complete?"Practice again ↗":"Earn evidence ↗"}</Link><b>{stage.complete?"✓ READY":"NOT READY"}</b></div></article>)}</div><section className={`npc-panel ${!unlocked?"locked":""}`}><div className="npc-panel-head"><div><span className="npc-avatar">AI</span><div><small>FINAL CHECKPOINT</small><strong>Airline service desk</strong></div></div><span className="mode-badge">{won?"BOSS CLEARED":unlocked?"GATE OPEN":"GATE LOCKED"}</span></div>{!unlocked?<div className="npc-lock"><strong>Build proof in all three skills.</strong><p>Complete a Vocabulary, Listening and Speaking activity successfully. The boss gate reads attempts from the backend.</p></div>:<><div className="objective-box"><small>CURRENT OBJECTIVE</small><strong>{won?"Success — the rebooking conversation is complete.":objective}</strong></div><div className="chat-log">{messages.map((m,i)=><div className={`chat-bubble ${m.role}`} key={i}><span>{m.role==="agent"?"Agent":"You"}</span><p>{m.content}</p></div>)}</div>{!won?<form className="chat-form" onSubmit={chat}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Type what you would say in English…"/><button className="button primary" disabled={busy||claiming}>{claiming?"Claiming reward…":busy?"Thinking…":"Send →"}</button></form>:<div className="boss-win"><span>✦</span><div><strong>Boss cleared +150 XP</strong><p>Airport Wings are now available in your World Map loadout.</p></div><Link href="/worlds" className="button primary">View rewards →</Link></div>}</>}</section></div>
}
