"use client";

import { useMemo, useState } from "react";
import { recordAttempt } from "@/lib/api";

const sentenceRounds = [
  { chunks: ["because", "public transport", "is", "more sustainable", "I prefer", "it"], answer: "I prefer public transport because it is more sustainable", skill: "Grammar" },
  { chunks: ["had already left", "when", "the gate", "I arrived at", "the flight"], answer: "The flight had already left when I arrived at the gate", skill: "Grammar" },
  { chunks: ["people", "who work remotely", "often value", "flexible schedules"], answer: "People who work remotely often value flexible schedules", skill: "Grammar" },
];

export function SentenceBuilder() {
  const [round,setRound]=useState(0);const [picked,setPicked]=useState<string[]>([]);const [result,setResult]=useState<null|boolean>(null);const current=sentenceRounds[round];
  const remaining=current.chunks.filter((_,i)=>!picked.includes(String(i)));
  const built=picked.map((id)=>current.chunks[Number(id)]).join(" ");
  function add(chunk:string){const idx=current.chunks.findIndex((v,i)=>v===chunk&&!picked.includes(String(i)));if(idx>=0&&result===null)setPicked((p)=>[...p,String(idx)])}
  function reset(){setPicked([]);setResult(null)}
  function check(){const correct=built.toLowerCase()===current.answer.toLowerCase();setResult(correct);recordAttempt({skill:"Grammar",activity:"sentence-builder",itemKey:`sentence:${round}`,prompt:current.answer,answer:current.answer,accuracy:correct?1:0}).catch(()=>{})}
  function next(){setRound((v)=>(v+1)%sentenceRounds.length);reset()}
  return <section className="mini-card"><div className="mini-head"><span className="eyebrow">SENTENCE BUILDER</span><b>{round+1}/{sentenceRounds.length}</b></div><h2>Build one natural sentence.</h2><div className={`sentence-drop ${result===true?"good":result===false?"bad":""}`}>{built||"Tap fragments in the correct order…"}</div><div className="fragment-bank">{remaining.map((chunk)=><button key={chunk} onClick={()=>add(chunk)}>{chunk}</button>)}</div><div className="mini-actions"><button className="button ghost" onClick={reset}>Reset</button>{result===null?<button className="button primary" onClick={check} disabled={!picked.length}>Check</button>:<button className="button primary" onClick={next}>{result?"Correct — next →":"See next →"}</button>}</div>{result===false&&<p className="mini-feedback">Natural answer: <strong>{current.answer}</strong>. This pattern was added to your review queue.</p>}</section>
}

const grammarRounds=[
  {prompt:"Choose the grammatically correct sentence.",answer:"Many people believe that public transport should be improved.",options:["Many people believes that public transport should be improved.","Many people believe that public transport should be improved.","Many people believing public transport should improved."]},
  {prompt:"Repair the conditional.",answer:"If I had left earlier, I would not have missed the flight.",options:["If I left earlier, I would not missed the flight.","If I had left earlier, I would not have missed the flight.","If I have left earlier, I would not missed the flight."]},
  {prompt:"Choose the natural relative clause.",answer:"The hotel that we booked was close to the station.",options:["The hotel what we booked was close to station.","The hotel that we booked was close to the station.","The hotel we booked it was close to the station."]},
];

export function GrammarRepair(){const [i,setI]=useState(0);const [chosen,setChosen]=useState("");const c=grammarRounds[i];const correct=chosen===c.answer;function choose(v:string){if(chosen)return;setChosen(v);recordAttempt({skill:"Grammar",activity:"grammar-repair",itemKey:`grammar:${i}`,prompt:c.prompt,answer:c.answer,accuracy:v===c.answer?1:0}).catch(()=>{})}function next(){setI((v)=>(v+1)%grammarRounds.length);setChosen("")}return <section className="mini-card"><div className="mini-head"><span className="eyebrow">GRAMMAR REPAIR</span><b>{i+1}/{grammarRounds.length}</b></div><h2>{c.prompt}</h2><div className="choice-stack">{c.options.map((v)=><button key={v} onClick={()=>choose(v)} className={chosen?v===c.answer?"correct":v===chosen?"wrong":"muted":""}>{v}</button>)}</div>{chosen&&<div className={`mini-feedback-box ${correct?"success":"error"}`}><span>{correct?"✓ Correct repair":"Review this pattern"}</span><strong>{c.answer}</strong><button className="button primary" onClick={next}>Next →</button></div>}</section>}

const collocations=[
  {core:"heavy",answer:"rain",options:["rain","idea","traffic","decision"]},
  {core:"make",answer:"a decision",options:["a decision","a rain","a traffic","a research"]},
  {core:"highly",answer:"effective",options:["effective","rain","traffic","journey"]},
  {core:"pose",answer:"a threat",options:["a threat","a homework","a transport","a weather"]},
];
export function CollocationFactory(){const [i,setI]=useState(0);const [chosen,setChosen]=useState("");const c=collocations[i];function pick(v:string){if(chosen)return;setChosen(v);recordAttempt({skill:"Vocabulary",activity:"collocation-factory",itemKey:`collocation:${c.core}`,prompt:`${c.core} ___`,answer:c.answer,accuracy:v===c.answer?1:0}).catch(()=>{})}return <section className="mini-card factory"><div className="mini-head"><span className="eyebrow">COLLOCATION FACTORY</span><b>{i+1}/{collocations.length}</b></div><div className="factory-core"><small>BUILD A NATURAL PAIR</small><strong>{c.core} + ?</strong></div><div className="factory-options">{c.options.map((v)=><button key={v} className={chosen?v===c.answer?"correct":v===chosen?"wrong":"muted":""} onClick={()=>pick(v)}>{v}</button>)}</div>{chosen&&<button className="button primary wide" onClick={()=>{setI((v)=>(v+1)%collocations.length);setChosen("")}}>Next batch →</button>}</section>}

const passages=[
  {text:"Cities around the world are experimenting with car-free zones. Supporters argue that restricting private vehicles can reduce air pollution and make streets safer for pedestrians. Critics, however, worry that small businesses may lose customers if access becomes less convenient. Early studies suggest the effect depends heavily on public transport quality and how gradually the policy is introduced.",q:"What does the passage say the success of car-free zones depends on?",answer:"Public transport quality and implementation",options:["Tourist numbers","Public transport quality and implementation","The number of parking spaces","Weather conditions"]},
  {text:"Remote work can give employees more control over their schedules, but it also changes how teams share informal knowledge. New employees may find it harder to learn unwritten routines when they rarely observe experienced colleagues. Some companies respond by pairing new staff with mentors and scheduling short, optional social sessions rather than adding more formal meetings.",q:"Why may new employees struggle in remote teams?",answer:"They miss informal observation",options:["They receive too much training","They miss informal observation","They work fewer hours","They have too many mentors"]},
];
export function ReadingRace(){const [i,setI]=useState(0);const [chosen,setChosen]=useState("");const c=passages[i];function pick(v:string){if(chosen)return;setChosen(v);recordAttempt({skill:"Reading",activity:"reading-race",itemKey:`reading:${i}`,prompt:c.q,answer:c.answer,accuracy:v===c.answer?1:0}).catch(()=>{})}return <section className="reading-race"><div className="reading-passage"><span className="eyebrow">READING RACE · SKIM / SCAN</span><p>{c.text}</p></div><div className="reading-question"><small>QUESTION {i+1}/{passages.length}</small><h2>{c.q}</h2><div className="choice-stack">{c.options.map((v)=><button key={v} className={chosen?v===c.answer?"correct":v===chosen?"wrong":"muted":""} onClick={()=>pick(v)}>{v}</button>)}</div>{chosen&&<button className="button primary" onClick={()=>{setI((v)=>(v+1)%passages.length);setChosen("")}}>Next passage →</button>}</div></section>}

const listeningRounds=[
  {audio:"Attention passengers. Flight VN218 to Da Nang will now depart from gate twelve instead of gate eight.",q:"What changed?",answer:"The departure gate",options:["The destination","The departure gate","The flight number","The airline"]},
  {audio:"The museum closes at six, but the last guided tour begins at four thirty in the afternoon.",q:"When does the last guided tour begin?",answer:"4:30 p.m.",options:["4:00 p.m.","4:30 p.m.","5:30 p.m.","6:00 p.m."]},
];
export function ListeningPick(){const [i,setI]=useState(0);const [chosen,setChosen]=useState("");const c=listeningRounds[i];function play(){if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(c.audio);u.lang="en-US";u.rate=.92;window.speechSynthesis.speak(u)}function pick(v:string){if(chosen)return;setChosen(v);recordAttempt({skill:"Listening",activity:"listen-pick",itemKey:`listen:${i}`,prompt:c.audio,answer:c.answer,accuracy:v===c.answer?1:0}).catch(()=>{})}return <section className="mini-card listening-game"><div className="mini-head"><span className="eyebrow">LISTEN & PICK</span><b>{i+1}/{listeningRounds.length}</b></div><button className="listen-orb" onClick={play}>▶<small>play announcement</small></button><h2>{c.q}</h2><div className="choice-stack">{c.options.map((v)=><button key={v} className={chosen?v===c.answer?"correct":v===chosen?"wrong":"muted":""} onClick={()=>pick(v)}>{v}</button>)}</div>{chosen&&<button className="button primary wide" onClick={()=>{setI((v)=>(v+1)%listeningRounds.length);setChosen("")}}>Next audio →</button>}</section>}

const storyNodes={start:{text:"You arrive at your hotel at 11:30 p.m., but the receptionist says there is no reservation under your name.",choices:[{label:"Show the confirmation email and politely ask them to check again.",next:"proof",score:1},{label:"Say: 'You wrong. Give room now.'",next:"rude",score:0}]},proof:{text:"The receptionist checks the confirmation number and finds that the booking was entered under your middle name.",choices:[{label:"Ask whether breakfast is included before taking the key.",next:"win",score:1},{label:"Leave without confirming anything.",next:"win",score:0}]},rude:{text:"The receptionist looks confused and asks you to explain the problem more clearly.",choices:[{label:"Rephrase calmly: 'I have a confirmed reservation. Could you check this number, please?'",next:"proof",score:1},{label:"Repeat the same sentence louder.",next:"lose",score:0}]},win:{text:"You solve the problem and check in successfully.",choices:[]},lose:{text:"The conversation breaks down. Try the story again with clearer, more polite language.",choices:[]}} as const;
export function StoryChoice(){const [node,setNode]=useState<keyof typeof storyNodes>("start");const [score,setScore]=useState(0);const current=storyNodes[node];function choose(choice:{label:string;next:string;score:number}){setScore((s)=>s+choice.score);recordAttempt({skill:"Reading",activity:"story-choice",itemKey:`story:${node}`,prompt:current.text,answer:choice.label,accuracy:choice.score}).catch(()=>{});setNode(choice.next as keyof typeof storyNodes)}const ended=current.choices.length===0;return <section className="story-card"><span className="eyebrow">STORY CHOICE · HOTEL</span><div className="story-scene"><small>SCENE</small><p>{current.text}</p></div>{!ended?<div className="story-choices">{current.choices.map((c)=><button key={c.label} onClick={()=>choose(c)}>{c.label}<span>→</span></button>)}</div>:<div className="story-end"><strong>{node==="win"?"Mission solved ✓":"Conversation failed"}</strong><p>Communication score: {score}</p><button className="button primary" onClick={()=>{setNode("start");setScore(0)}}>Play again</button></div>}</section>}
