"use client";
import{useMemo,useState}from"react";import{recordAttempt}from"@/lib/api";import{getLearningPack}from"@/data/contentPacks";

type PackProps={pack?:string};
export { default as SentenceBuilder } from "./learning/VerifiedSentenceBuilder";

export function GrammarRepair({pack="default"}:PackProps){const rounds=getLearningPack(pack).grammarRounds;const[i,setI]=useState(0);const[chosen,setChosen]=useState("");const c=rounds[i%rounds.length];const correct=chosen===c.answer;function choose(v:string){if(chosen)return;setChosen(v);recordAttempt({skill:"Grammar",activity:"grammar-repair",itemKey:`${pack}:grammar:${i}`,prompt:c.prompt,answer:c.answer,accuracy:v===c.answer?1:0}).catch(()=>{})}function next(){setI(v=>(v+1)%rounds.length);setChosen("")}return <section className="mini-card"><div className="mini-head"><span className="eyebrow">GRAMMAR REPAIR · {getLearningPack(pack).label}</span><b>{i+1}/{rounds.length}</b></div><h2>{c.prompt}</h2><div className="choice-stack">{c.options.map(v=><button key={v} onClick={()=>choose(v)} className={chosen?v===c.answer?"correct":v===chosen?"wrong":"muted":""}>{v}</button>)}</div>{chosen&&<div className={`mini-feedback-box ${correct?"success":"error"}`}><span>{correct?"✓ Correct repair":"Review this pattern"}</span><strong>{c.answer}</strong><button className="button primary" onClick={next}>Next →</button></div>}</section>}

export { default as CollocationFactory } from "./learning/VerifiedCollocationFactory";

export { default as ReadingRace } from "./learning/VerifiedReadingRace";

export function ListeningPick({pack="default"}:PackProps){const rounds=getLearningPack(pack).listeningRounds;const[i,setI]=useState(0);const[chosen,setChosen]=useState("");const c=rounds[i%rounds.length];function play(){if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(c.audio);u.lang="en-US";u.rate=.92;window.speechSynthesis.speak(u)}function pick(v:string){if(chosen)return;setChosen(v);recordAttempt({skill:"Listening",activity:"listen-pick",itemKey:`${pack}:listen:${i}`,prompt:c.audio,answer:c.answer,accuracy:v===c.answer?1:0}).catch(()=>{})}return <section className="mini-card listening-game"><div className="mini-head"><span className="eyebrow">LISTEN & PICK · {getLearningPack(pack).label}</span><b>{i+1}/{rounds.length}</b></div><button className="listen-orb" onClick={play}>▶<small>play announcement</small></button><h2>{c.q}</h2><div className="choice-stack">{c.options.map(v=><button key={v} className={chosen?v===c.answer?"correct":v===chosen?"wrong":"muted":""} onClick={()=>pick(v)}>{v}</button>)}</div>{chosen&&<button className="button primary wide" onClick={()=>{setI(v=>(v+1)%rounds.length);setChosen("")}}>Next audio →</button>}</section>}

const storyNodes={start:{text:"You arrive at your hotel at 11:30 p.m., but the receptionist says there is no reservation under your name.",choices:[{label:"Show the confirmation email and politely ask them to check again.",next:"proof",score:1},{label:"Say: 'You wrong. Give room now.'",next:"rude",score:0}]},proof:{text:"The receptionist checks the confirmation number and finds that the booking was entered under your middle name.",choices:[{label:"Ask whether breakfast is included before taking the key.",next:"win",score:1},{label:"Leave without confirming anything.",next:"win",score:0}]},rude:{text:"The receptionist looks confused and asks you to explain the problem more clearly.",choices:[{label:"Rephrase calmly: 'I have a confirmed reservation. Could you check this number, please?'",next:"proof",score:1},{label:"Repeat the same sentence louder.",next:"lose",score:0}]},win:{text:"You solve the problem and check in successfully.",choices:[]},lose:{text:"The conversation breaks down. Try the story again with clearer, more polite language.",choices:[]}} as const;
export function StoryChoice(){const[node,setNode]=useState<keyof typeof storyNodes>("start");const[score,setScore]=useState(0);const current=storyNodes[node];function choose(choice:{label:string;next:string;score:number}){setScore(s=>s+choice.score);recordAttempt({skill:"Reading",activity:"story-choice",itemKey:`story:${node}`,prompt:current.text,answer:choice.label,accuracy:choice.score}).catch(()=>{});setNode(choice.next as keyof typeof storyNodes)}const ended=current.choices.length===0;return <section className="story-card"><span className="eyebrow">STORY CHOICE · HOTEL</span><div className="story-scene"><small>SCENE</small><p>{current.text}</p></div>{!ended?<div className="story-choices">{current.choices.map(c=><button key={c.label} onClick={()=>choose(c)}>{c.label}<span>→</span></button>)}</div>:<div className="story-end"><strong>{node==="win"?"Mission solved ✓":"Conversation failed"}</strong><p>Communication score: {score}</p><button className="button primary" onClick={()=>{setNode("start");setScore(0)}}>Play again</button></div>}</section>}
