"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { getPlayerProfile, PlayerProfile, recordAttempt, savePlayerProfile } from "@/lib/api";
import { playLearningAudio } from "@/lib/tts";

type Skill="Vocabulary"|"Grammar"|"Reading"|"Listening";
type Question={skill:Skill;prompt:string;context?:string;audio?:string;options:string[];answer:string};

const questions:Question[]=[
 {skill:"Vocabulary",prompt:"What does “borrow” mean?",options:["Take something temporarily and return it","Give something away forever","Pay for something twice","Break something accidentally"],answer:"Take something temporarily and return it"},
 {skill:"Grammar",prompt:"She ___ to work by bus every day.",options:["go","goes","going","has go"],answer:"goes"},
 {skill:"Listening",prompt:"Listen and choose the new meeting time.",audio:"The meeting was originally at two o'clock, but it has been moved to three thirty this afternoon.",options:["2:00","2:30","3:00","3:30"],answer:"3:30"},
 {skill:"Reading",prompt:"Why should visitors arrive earlier?",context:"The library will close at five today for maintenance. Visitors who need to print documents should arrive before four thirty because the printers will be shut down first.",options:["The library opens late","The printers close before the library","Printing is free before four thirty","Maintenance starts tomorrow"],answer:"The printers close before the library"},
 {skill:"Vocabulary",prompt:"Which meaning is closest to “reliable”?",options:["Can be trusted to work well","Very expensive","Difficult to explain","Recently invented"],answer:"Can be trusted to work well"},
 {skill:"Grammar",prompt:"I ___ on this project since March.",options:["work","worked","have worked","am work"],answer:"have worked"},
 {skill:"Reading",prompt:"What problem does the company try to solve?",context:"Remote staff liked flexible hours, but new employees said they learned slowly because they rarely overheard experienced colleagues solving everyday problems. The company introduced weekly mentor sessions rather than adding more formal training videos.",options:["Employees work too many hours","New staff miss informal learning","Training videos are too expensive","Mentors want fewer meetings"],answer:"New staff miss informal learning"},
 {skill:"Listening",prompt:"What should workshop participants do?",audio:"Although the ten o'clock workshop is still happening, it has moved from room two fourteen to the conference room on the ground floor. Please go directly there rather than checking in upstairs.",options:["Arrive at eleven","Go to room 214","Go directly to the ground-floor conference room","Check in upstairs first"],answer:"Go directly to the ground-floor conference room"},
 {skill:"Grammar",prompt:"If we had tested the edge case earlier, we ___ the issue before release.",options:["find","would find","would have found","had found"],answer:"would have found"},
 {skill:"Vocabulary",prompt:"What does “mitigate a risk” mean?",options:["Ignore a risk","Reduce its likelihood or impact","Transfer every responsibility","Describe it in more detail"],answer:"Reduce its likelihood or impact"},
 {skill:"Reading",prompt:"Which interpretation best matches the writer?",context:"The pilot policy did not fail outright: traffic fell in the centre and air quality improved slightly. Yet retailers reported uneven effects, and neighbourhoods without frequent bus services saw less benefit. The evidence therefore supports expansion only if transport access improves at the same time.",options:["The policy should be abandoned everywhere","The policy succeeded equally in every area","Expansion is conditional on better transport access","Retail effects are more important than air quality"],answer:"Expansion is conditional on better transport access"},
 {skill:"Grammar",prompt:"Choose the natural advanced conditional.",options:["Had I known about the change, I would have prepared differently.","Had I knew about the change, I prepare differently.","If I would know the change, I had prepared differently.","Knowing the change, I would prepared different."],answer:"Had I known about the change, I would have prepared differently."},
];

const goalRoute:Record<PlayerProfile["goal"],string>={travel:"/travel",conversation:"/conversation",work:"/work",ielts:"/ielts"};
const goalName:Record<PlayerProfile["goal"],string>={travel:"Travel District",conversation:"Conversation District",work:"Work District",ielts:"IELTS Tower"};

function estimateLevel(score:number):PlayerProfile["cefrLevel"]{if(score<=2)return"A1";if(score<=4)return"A2";if(score<=7)return"B1";if(score<=9)return"B2";return"C1"}

export default function PlacementRun(){
 const[index,setIndex]=useState(0);const[answers,setAnswers]=useState<Record<number,string>>({});const[busy,setBusy]=useState(false);const[result,setResult]=useState<{level:PlayerProfile["cefrLevel"];score:number;profile:PlayerProfile;skillScores:Record<Skill,number>}|null>(null);const[error,setError]=useState("");const question=questions[index];const chosen=answers[index];const progress=Math.round((Object.keys(answers).length/questions.length)*100);
 const skillPreview=useMemo(()=>{const out={} as Record<Skill,{correct:number;total:number}>;for(const skill of["Vocabulary","Grammar","Reading","Listening"]as Skill[])out[skill]={correct:0,total:0};questions.forEach((q,i)=>{out[q.skill].total+=1;if(answers[i]===q.answer)out[q.skill].correct+=1});return out},[answers]);
 async function playAudio(){if(question.audio)await playLearningAudio(question.audio,.92)}
 function choose(value:string){setAnswers(v=>({...v,[index]:value}))}
 function next(){if(index<questions.length-1){setIndex(v=>v+1);return}void finish()}
 async function finish(){if(Object.keys(answers).length<questions.length)return;setBusy(true);setError("");const score=questions.reduce((sum,q,i)=>sum+(answers[i]===q.answer?1:0),0);const level=estimateLevel(score);const skillScores={}as Record<Skill,number>;for(const skill of["Vocabulary","Grammar","Reading","Listening"]as Skill[]){const rows=questions.map((q,i)=>({q,i})).filter(x=>x.q.skill===skill);skillScores[skill]=rows.filter(x=>answers[x.i]===x.q.answer).length/rows.length}try{let profile:PlayerProfile;try{profile=await getPlayerProfile()}catch{const raw=localStorage.getItem("loccao_player_build");const local=raw?JSON.parse(raw):{};profile={userId:"local",goal:local.goal||"conversation",cefrLevel:local.cefrLevel||"B1",dailyMinutes:local.dailyMinutes||15,targetBand:local.targetBand||7,interests:local.interests||["daily-life"],onboarded:true,updatedAt:new Date().toISOString()}}await Promise.all((Object.keys(skillScores)as Skill[]).map(skill=>recordAttempt({skill,activity:"placement",itemKey:`placement:${skill.toLowerCase()}`,prompt:`Calibration signal for ${skill}`,answer:`Strengthen ${skill} through campaign play`,accuracy:skillScores[skill]}).catch(()=>null)));let saved=profile;try{saved=await savePlayerProfile({goal:profile.goal,cefrLevel:level,dailyMinutes:profile.dailyMinutes,targetBand:profile.targetBand,interests:profile.interests})}catch{saved={...profile,cefrLevel:level};localStorage.setItem("loccao_player_build",JSON.stringify({goal:saved.goal,cefrLevel:level,dailyMinutes:saved.dailyMinutes,targetBand:saved.targetBand,interests:saved.interests}))}localStorage.setItem("loccao_placement_result",JSON.stringify({level,score,at:new Date().toISOString()}));setResult({level,score,profile:saved,skillScores})}catch(e){setError(e instanceof Error?e.message:"Could not save calibration") }finally{setBusy(false)}}
 if(result)return <div className="placement-result"><section className="progression-hero"><div><span className="eyebrow light">CALIBRATION COMPLETE</span><h1>Starting rank: {result.level}</h1><p>This is a gameplay starting estimate, not an official CEFR certification. Your rank will keep adjusting as real Reading, Listening, Speaking and Writing evidence arrives.</p></div><div className="hero-level-orb"><strong>{result.score}</strong><small>/ 12</small></div></section><section className="panel"><div className="section-heading"><div><span className="eyebrow">SKILL SIGNALS</span><h2>Your first learning fingerprint</h2></div></div><div className="placement-skills">{(Object.keys(result.skillScores)as Skill[]).map(skill=><div className="placement-skill" key={skill}><span>{skill}</span><strong>{Math.round(result.skillScores[skill]*100)}%</strong><div className="progress"><i style={{width:`${result.skillScores[skill]*100}%`}}/></div></div>)}</div><div className="calibration-note"><strong>Speaking and Writing are intentionally not guessed here.</strong><p>They will calibrate from microphone/writing evidence during play.</p></div><Link className="button primary wide" href={goalRoute[result.profile.goal]}>Start main quest: {goalName[result.profile.goal]} →</Link></section></div>;
 return <div className="placement-shell"><section className="placement-top"><div><span className="eyebrow">PROLOGUE · CALIBRATION RUN</span><h1>Find your starting rank.</h1><p>12 quick signals. No certificate, no exam theatre — just enough information to stop the game from treating everyone the same.</p></div><strong>{index+1}/12</strong></section><div className="progress large"><i style={{width:`${progress}%`}}/></div><section className="placement-question"><div className="placement-meta"><span>{question.skill}</span><small>Question {index+1}</small></div>{question.context&&<blockquote>{question.context}</blockquote>}{question.audio&&<button className="listen-orb placement-audio" onClick={()=>void playAudio()}>▶<small>play audio</small></button>}<h2>{question.prompt}</h2><div className="choice-stack">{question.options.map(option=><button className={chosen===option?"correct":""} key={option} onClick={()=>choose(option)}>{option}</button>)}</div><div className="placement-actions"><button className="button ghost" disabled={index===0} onClick={()=>setIndex(v=>Math.max(0,v-1))}>← Back</button><button className="button primary" disabled={!chosen||busy} onClick={next}>{busy?"Calibrating…":index===questions.length-1?"Finish calibration →":"Lock answer →"}</button></div></section><aside className="panel placement-signal"><span className="eyebrow">LIVE SIGNAL</span><div className="placement-mini-grid">{(Object.keys(skillPreview)as Skill[]).map(skill=><div key={skill}><span>{skill}</span><b>{skillPreview[skill].correct}/{skillPreview[skill].total}</b></div>)}</div><p className="muted">Answers are scored only when you finish. You can go back and change any choice.</p>{error&&<p className="notice error">{error}</p>}</aside></div>
}
