"use client";

import Link from "next/link";
import GameArt from "./GameArt";
import { useEffect, useMemo, useState } from "react";
import { getMe, getPlayerProfile, getProgression, Me, PlayerProfile, ProgressionState } from "@/lib/api";

export default function PlayerProfilePanel(){
  const [me,setMe]=useState<Me|null>(null);const[profile,setProfile]=useState<PlayerProfile|null>(null);const[progress,setProgress]=useState<ProgressionState|null>(null);const[error,setError]=useState("");
  useEffect(()=>{Promise.all([getMe(),getPlayerProfile(),getProgression()]).then(([m,p,g])=>{setMe(m);setProfile(p);setProgress(g)}).catch(e=>setError(e instanceof Error?e.message:"Player profile unavailable"))},[]);
  const equipped=useMemo(()=>progress?.inventory.filter(i=>i.equipped)??[],[progress]);
  if(!me||!profile||!progress)return <section className="panel profile-game-card"><span className="eyebrow">PLAYER PROFILE</span><h2>{error?"Profile offline":"Loading your character…"}</h2><p>{error||"Reading build, level, achievements and equipped rewards."}</p></section>;
  const pct=Math.min(100,Math.round(progress.xpIntoLevel/progress.xpForNext*100));
  return <div className="player-profile-layout"><section className="profile-hero-card"><GameArt id={profile.goal==="travel"?"may":profile.goal==="work"?"soi":profile.goal==="conversation"?"nang":"mam"} className="profile-avatar-xl" label={`${me.user.displayName}’s village companion`}/><div className="profile-identity"><span className="eyebrow light">PLAYER CARD</span><h1>{me.user.displayName}</h1><p>Level {progress.level} · {me.user.xp.toLocaleString()} XP · 🔥 {me.user.streak} day streak</p><div className="progress large"><i style={{width:`${pct}%`}}/></div><small>{progress.xpIntoLevel}/{progress.xpForNext} XP to level {progress.level+1}</small></div><div className="profile-build"><small>BUILD</small><strong>{profile.goal.toUpperCase()}</strong><span>{profile.cefrLevel} · {profile.dailyMinutes} min/day</span>{profile.goal==="ielts"&&<span>Target {profile.targetBand.toFixed(1)}</span>}</div></section><section className="profile-grid"><article className="panel"><div className="section-heading"><div><span className="eyebrow">LOADOUT</span><h2>Equipped rewards</h2></div><Link href="/progress" className="text-link">Change loadout →</Link></div>{equipped.length===0?<div className="empty-reward"><strong>No trophies equipped yet.</strong><p>Unlock worlds, clear bosses and earn achievements to build your identity.</p></div>:<div className="equipped-list">{equipped.map(item=><div className="equipped-item" key={item.id}><span>{item.slot}</span><strong>{item.name}</strong><p>{item.description}</p></div>)}</div>}</article><article className="panel"><div className="section-heading"><div><span className="eyebrow">ACHIEVEMENTS</span><h2>{progress.achievements.filter(a=>a.unlocked).length}/{progress.achievements.length} earned</h2></div></div><div className="profile-achievements">{progress.achievements.map(a=><div className={a.unlocked?"earned":""} key={a.id}><span>{a.icon}</span><div><strong>{a.title}</strong><small>{a.unlocked?"Unlocked":`${a.progress}/${a.target}`}</small></div></div>)}</div></article></section><section className="panel profile-actions"><div><span className="eyebrow">YOUR BUILD</span><h2>Change the adventure, not the account.</h2><p>Your goal and daily time shape the quest director. Your account adventure remains available from Back to village.</p></div><Link href="/onboarding" className="button primary">Retune build →</Link></section></div>
}
