"use client";

import { useMemo, useState } from "react";
import { scoreWriting, WritingScore } from "@/lib/api";

const task = "Some people believe that governments should invest more money in public transport than in building new roads. To what extent do you agree or disagree?";
const connectors=["however","therefore","moreover","furthermore","although","because","consequently","nevertheless","while","whereas","firstly","secondly","overall"];
const clamp=(v:number)=>Math.min(8,Math.max(4,v));const half=(v:number)=>Math.round(v*2)/2;

export default function WritingLab(){
 const [text,setText]=useState("");const [submitted,setSubmitted]=useState(false);const [busy,setBusy]=useState(false);const [remote,setRemote]=useState<WritingScore|null>(null);const [mode,setMode]=useState("local fallback ready");
 const stats=useMemo(()=>{const words=text.trim()?text.trim().split(/\s+/):[];const lower=text.toLowerCase();const paragraphs=text.split(/\n\s*\n/).filter((x)=>x.trim()).length;const connectorCount=connectors.filter((w)=>lower.includes(w)).length;const unique=new Set(words.map((w)=>w.toLowerCase().replace(/[^a-z]/g,"")).filter(Boolean)).size;const lexicalRatio=words.length?unique/words.length:0;const sentences=text.split(/[.!?]+/).filter((x)=>x.trim());const avgSentence=sentences.length?words.length/sentences.length:0;const taskResponse=half(clamp(4+(words.length>=120?1:0)+(words.length>=220?1:0)+(words.length>=250?.5:0)+(paragraphs>=3?.5:0)));const coherence=half(clamp(4+Math.min(1.5,connectorCount*.25)+(paragraphs>=4?1:paragraphs>=2?.5:0)+(avgSentence>=10&&avgSentence<=28?.5:0)));const lexical=half(clamp(4+(words.length>=150?.5:0)+(lexicalRatio>=.55?1.5:lexicalRatio>=.42?1:.5)+(words.length>=250?.5:0)));const grammar=half(clamp(4+(sentences.length>=8?.75:.25)+(avgSentence>=12?.75:.25)+(lower.includes("although")||lower.includes("while")||lower.includes("whereas")?.5:0)));const overall=half((taskResponse+coherence+lexical+grammar)/4);return{words:words.length,paragraphs,connectorCount,taskResponse,coherence,lexical,grammar,overall}},[text]);
 async function submit(){setSubmitted(true);setBusy(true);setRemote(null);try{const value=await scoreWriting(text,task);setRemote(value);setMode(value.provider)}catch{setMode("local browser heuristic")}finally{setBusy(false)}}
 const overall=remote?.overall??stats.overall;const criteria=remote?.criteria??{taskResponse:stats.taskResponse,coherenceCohesion:stats.coherence,lexicalResource:stats.lexical,grammarRangeAccuracy:stats.grammar};
 const notes=remote?.improvements??[stats.words>=250?"You reached the expected Task 2 length.":"Build toward 250+ words with a clearer developed position.",stats.connectorCount>=4?"Linking devices are visible; now check that each one expresses a real logical relationship.":"Add linking devices only where the logic needs them.",stats.paragraphs>=4?"Paragraph structure is visible.":"Use a clear introduction, body paragraphs and conclusion."];
 return <div className="writing-layout"><section className="writing-workspace"><div className="task-box"><span>IELTS WRITING TASK 2</span><p>{task}</p><small>Write at least 250 words. Suggested time: 40 minutes.</small></div><textarea className="practice-textarea essay" value={text} onChange={(e)=>{setText(e.target.value);setSubmitted(false);setRemote(null)}} placeholder="Write your essay here…"/><div className="editor-footer"><span className={stats.words>=250?"good":""}>{stats.words} words</span><span>{stats.paragraphs} paragraphs</span><span className="engine-label">{mode}</span><button className="button primary" disabled={stats.words<40||busy} onClick={submit}>{busy?"Scoring…":"Estimate band"}</button></div></section><aside className="score-panel"><div><span className="eyebrow">PRACTICE ESTIMATE</span><div className="big-band">{submitted?overall.toFixed(1):"—"}<small>band</small></div><p>{remote?.disclaimer||"Practice estimate only. When the AI service is unavailable, the browser uses transparent local heuristics instead."}</p></div><div className="rubric-list">{[["Task Response",criteria.taskResponse],["Coherence & Cohesion",criteria.coherenceCohesion],["Lexical Resource",criteria.lexicalResource],["Grammar Range & Accuracy",criteria.grammarRangeAccuracy]].map(([label,value])=><div className="rubric" key={String(label)}><div><strong>{label}</strong><b>{submitted?Number(value).toFixed(1):"—"}</b></div><div className="progress"><i style={{width:submitted?`${Number(value)/9*100}%`:"0%"}}/></div></div>)}</div>{submitted&&<div className="coach-notes"><strong>{remote?"AI coach priorities":"Local coach priorities"}</strong><ul>{notes.map((note)=><li key={note}>{note}</li>)}</ul>{remote?.rewriteExample&&<div className="rewrite-tip"><small>REVISION PRINCIPLE</small><p>{remote.rewriteExample}</p></div>}</div>}</aside></div>
}
