package engine

import "strings"

type ScenarioEvaluation struct{BossID string `json:"bossId"`;Stage int `json:"stage"`;Score int `json:"score"`;Complete bool `json:"complete"`;Completed []string `json:"completed"`;Missing []string `json:"missing"`}
type scenarioObjective struct{Name string;Keywords []string}
func EvaluateBossConversation(bossID string,messages []string)ScenarioEvaluation{objectives:=objectivesForBoss(bossID);joined:=strings.ToLower(strings.Join(messages," "));result:=ScenarioEvaluation{BossID:bossID,Completed:[]string{},Missing:[]string{}};for _,objective:=range objectives{if containsAny(joined,objective.Keywords){result.Completed=append(result.Completed,objective.Name)}else{result.Missing=append(result.Missing,objective.Name)}};result.Stage=len(result.Completed);if len(objectives)>0{result.Score=int(float64(len(result.Completed))/float64(len(objectives))*100)};result.Complete=len(messages)>=3&&len(result.Missing)==0;return result}
func objectivesForBoss(bossID string)[]scenarioObjective{switch bossID{case"airport-crisis":return[]scenarioObjective{{"Explain the flight problem",[]string{"missed","miss my","late","delay"}},{"Ask for a workable replacement",[]string{"rebook","next flight","earliest","later flight","another flight","prefer"}},{"Confirm the plan",[]string{"book it","take it","yes please","gate","boarding","board"}}};case"hotel-reservation":return[]scenarioObjective{{"Explain the missing reservation",[]string{"reservation","booking","booked","cannot find","can't find"}},{"Provide booking evidence",[]string{"confirmation number","booking number","email","under my name","middle name"}},{"Confirm a practical stay detail",[]string{"breakfast","checkout","check-out","wifi","wi-fi","key card","please","could you"}}};case"city-transit":return[]scenarioObjective{{"Explain the destination or last-train problem",[]string{"station","train","metro","last train","get to","need to go"}},{"Ask for or choose a route",[]string{"fastest","route","transfer","change","line","fewer transfers"}},{"Confirm an operational detail",[]string{"platform","ticket","minutes","what time","central","blue line","green line"}}};case"cafe-connection":return[]scenarioObjective{{"Introduce yourself",[]string{"i'm ","i am ","my name is","call me"}},{"Show curiosity about the other person",[]string{"what about you","where are you","what do you","do you like","how about you"}},{"Keep or close the connection naturally",[]string{"nice to meet","good to meet","see you","would you like","can we","talk again"}}};case"weekend-plans":return[]scenarioObjective{{"Make a suggestion",[]string{"let's","how about","would you like","we could","why don't we"}},{"Agree on a time or place",[]string{"saturday","sunday","tomorrow","at ","meet at","cafe","park","cinema","where should"}},{"Confirm the final plan",[]string{"sounds good","see you","so we meet","it's a plan","perfect","confirmed"}}};case"repair-misunderstanding":return[]scenarioObjective{{"Signal the misunderstanding politely",[]string{"sorry","didn't understand","did not understand","what do you mean","not sure what you mean"}},{"Rephrase the intended meaning",[]string{"what i mean","in other words","i meant","let me explain","to clarify"}},{"Confirm shared understanding",[]string{"so you mean","got it","i understand","that makes sense","okay now","now i understand"}}};default:return nil}}
func containsAny(text string,keywords []string)bool{for _,keyword:=range keywords{if strings.Contains(text,keyword){return true}};return false}
